### ISSUE TITLE
How can I use this package for my own modules

### ISSUE THREAD

**Issue by rencber** [tushortz/More-Python-Completions#1]
How can I use this package for my own modules , -i with this I can't see my own modules.

**Comment by tushortz** [comment]
Hello @rencber . There is no support for external modules at the moment. I began working on another package called `intellekt` but development is currently on hold

**Comment by tushortz** [comment]
check this out - https://github.com/sublimelsp/LSP-pyright

**Comment by rencber** [comment]
Thanks for the reply. Yes, it worked but of course, if it was just run by your code could be better, maybe I can modify your code or make an addition for that after the time I spend on coding. Your code is great, thanks.

**Comment by tushortz** [comment]
Thanks for your kind word.

you can clone or fork my repo and tweak it a bit to suit your code
